import '@mantine/core/styles.css';
import type { Metadata } from "next";
import localFont from 'next/font/local';


import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import "./globals.css";

export const satoshi = localFont({
  src: '../public/fonts/Satoshi-Variable.woff2',
  variable: '--font-satoshi',
  weight: '100 900', // variable font range
  display: 'swap',
});

export const metadata: Metadata = {
  title: "job portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${satoshi.className} antialiased`}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
